baseURL: "https://resplendent-maamoul-c44542.netlify.app/"
title: j91
paginate: 9
theme: coyote

# params:
#   profile:
#     enabled: true
#     name: John Doe
#     description: I've got something to tell you now, Walkman
#   social:
#     - name: github
#       url: https://resplendent-maamoul-c44542.netlify.app/

menu:
  main:
    - identifier: search
      name: Search
      url: search/
outputs:
    home:
        - HTML
        - JSON
